# Generated by Django 4.2.18 on 2025-01-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('difficulty', models.CharField(choices=[('1', 'easy'), ('2', 'medium'), ('3', 'hard')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.CharField(blank=True, max_length=100, null=True)),
                ('file_path', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(choices=[('uk', 'UK'), ('us', 'US')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('definition', models.CharField(max_length=100)),
                ('example', models.TextField()),
                ('phonetic_uk', models.CharField(blank=True, max_length=100)),
                ('phonetic', models.CharField(blank=True, max_length=100)),
                ('phonetic_us', models.CharField(blank=True, max_length=100)),
                ('rating', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
            ],
        ),
    ]
