# Generated by Django 4.2.18 on 2025-02-01 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_userword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWord',
        ),
    ]
