# Generated by Django 4.2.18 on 2025-02-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_userword'),
    ]

    operations = [
        migrations.AddField(
            model_name='userword',
            name='correct_streak',
            field=models.IntegerField(default=0),
        ),
    ]
