# Generated by Django 4.2.18 on 2025-02-02 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0005_userword_correct_streak'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaskWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', '新单词'), ('retry', '需复习'), ('known', '已掌握')], default='new', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='userword',
            name='history_intervals',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userword',
            name='initial_strength',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='userword',
            name='lock_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userword',
            name='memory_phase',
            field=models.CharField(choices=[('initial', '初次学习'), ('retention', '保持阶段'), ('mastered', '完全掌握')], default='initial', max_length=20),
        ),
        migrations.AddField(
            model_name='userword',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userword',
            name='next_review',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='userword',
            index=models.Index(fields=['user', 'next_review'], name='learning_us_user_id_4f8cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='userword',
            index=models.Index(fields=['priority'], name='learning_us_priorit_71995d_idx'),
        ),
        migrations.AddField(
            model_name='taskword',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.dailytask'),
        ),
        migrations.AddField(
            model_name='taskword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.userword'),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='words',
            field=models.ManyToManyField(through='learning.TaskWord', to='learning.userword'),
        ),
        migrations.AlterUniqueTogether(
            name='taskword',
            unique_together={('task', 'word')},
        ),
        migrations.AlterUniqueTogether(
            name='dailytask',
            unique_together={('user', 'date')},
        ),
    ]
